<a href="https://colab.research.google.com/github/jeniferGoncalvesDaSilvaDev/algo_min_max_tic_tac_toe/blob/main/connect_four_agents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import random

ROWS = 6
COLS = 7

def create_board():
    return np.zeros((ROWS, COLS), dtype=int)

def valid_moves(board):
    return [c for c in range(COLS) if board[0][c] == 0]

def drop_piece(board, col, piece):
    for r in range(ROWS-1, -1, -1):
        if board[r][col] == 0:
            board[r][col] = piece
            return

def check_win(board, piece):
    # Horizontal
    for r in range(ROWS):
        for c in range(COLS-3):
            if all(board[r][c+i] == piece for i in range(4)):
                return True

    # Vertical
    for r in range(ROWS-3):
        for c in range(COLS):
            if all(board[r+i][c] == piece for i in range(4)):
                return True

    # Diagonal positiva
    for r in range(ROWS-3):
        for c in range(COLS-3):
            if all(board[r+i][c+i] == piece for i in range(4)):
                return True

    # Diagonal negativa
    for r in range(3, ROWS):
        for c in range(COLS-3):
            if all(board[r-i][c+i] == piece for i in range(4)):
                return True

    return False

# -------------------------
# AGENTE 1: ALEATÓRIO
# -------------------------
def agent_random(board, piece):
    return random.choice(valid_moves(board))

# -------------------------
# AGENTE 2: BLOQUEIA OU VENCE
# -------------------------
def agent_rule_based(board, piece):
    opponent = 1 if piece == 2 else 2

    # Tentar vencer
    for col in valid_moves(board):
        temp = board.copy()
        drop_piece(temp, col, piece)
        if check_win(temp, piece):
            return col

    # Bloquear vitória do oponente
    for col in valid_moves(board):
        temp = board.copy()
        drop_piece(temp, col, opponent)
        if check_win(temp, opponent):
            return col

    # Caso contrário, joga aleatório
    return random.choice(valid_moves(board))


# ==========================
#     LOOP DO JOGO
# ==========================

def play_game():
    board = create_board()
    turn = 1

    while True:
        if turn == 1:
            col = agent_random(board, 1)
        else:
            col = agent_rule_based(board, 2)

        drop_piece(board, col, turn)

        if check_win(board, turn):
            print(board)
            print(f"Jogador {turn} venceu!")
            return turn

        if len(valid_moves(board)) == 0:
            print(board)
            print("Empate!")
            return 0

        turn = 2 if turn == 1 else 1


# Rodar uma partida
winner = play_game()

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 1 0 1 0 2]
 [1 0 2 2 2 2 1]]
Jogador 2 venceu!


In [41]:
num_simulations = 10
player1_wins, player2_wins, draws = run_simulations(num_simulations)

player1_win_percentage = (player1_wins / num_simulations) * 100
player2_win_percentage = (player2_wins / num_simulations) * 100
draw_percentage = (draws / num_simulations) * 100

print(f"Player 1 (Random Agent) Win Percentage: {player1_win_percentage:.2f}%")
print(f"Player 2 (Rule-Based Agent) Win Percentage: {player2_win_percentage:.2f}%")
print(f"Draw Percentage: {draw_percentage:.2f}%")

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [1 1 2 2 2 2 1]]
Jogador 2 venceu!
[[1 0 0 0 0 0 0]
 [2 0 0 0 0 0 2]
 [1 0 0 0 0 0 2]
 [2 0 0 0 1 0 2]
 [1 0 2 0 1 0 2]
 [1 1 1 2 2 0 1]]
Jogador 2 venceu!
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 2 0 0 1 0 0]
 [0 2 2 2 2 1 0]
 [0 1 1 2 1 2 0]
 [1 2 1 1 1 2 0]]
Jogador 2 venceu!
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 2 0 1]
 [1 1 2 2 2 2 1]]
Jogador 2 venceu!
[[0 0 0 0 0 1 0]
 [0 0 0 0 1 2 0]
 [0 0 2 2 2 2 0]
 [0 0 1 1 1 2 0]
 [0 0 2 2 1 1 1]
 [1 0 1 2 2 1 2]]
Jogador 2 venceu!
[[0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [2 0 0 0 0 2 0]
 [1 1 0 1 0 2 1]
 [1 1 2 2 1 2 2]
 [1 2 2 1 1 2 1]]
Jogador 2 venceu!
[[0 0 1 0 0 0 0]
 [0 2 2 0 0 0 1]
 [2 2 1 0 0 0 2]
 [1 2 1 2 0 0 2]
 [1 2 1 1 2 0 1]
 [1 1 2 1 2 1 2]]
Jogador 2 venceu!
[[0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 2 0 0 0 1]
 [0 1 2 1 0 0 1]
 [0 1 1 2 1 2 2]]
Jogador 2 venceu!
[[1 2 0 0 0 0 0]
 [2 1 0 0 0 0 0